feign:
  hystrix:
    enabled: false
  client:
    config:
      default:   # 配置全局的Feign的调用超时时间，如果有指定的服务配置，默认的配置不会生效
        connectTimeout: 60000 # 指定的是消费者连接服务提供者的连接超时时间，是否能连接，单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的服务的超时时间，单位是毫秒
