#mybatis:
#  config-location: classpath:config/mybatis-config.xml
#  mapper-locations: classpath*:mybatis/**/*.xml

mybatis-plus:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  # type-aliases-package: com.baayso.**.domain
  # 配置扫描通用枚举
  type-enums-package: com.baayso.**.domain.enums
  # 指定 MyBatis 的执行器
  executor-type: REUSE
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-value: 'true' # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 'false' # 逻辑未删除值(默认为 0)
