spring:
  redis:
    database: 8
    host: 192.168.1.222
    port: 6379
    password:
    jedis:
      pool:
        max-active: 2048
        max-idle: 10
        max-wait: -1ms
        min-idle: 0
    timeout: 0ms
